using UnityEngine;

public class Controller : MonoBehaviour
{
    [SerializeField] private Iscp_ControlPublisher publisher;

    // Inputs
    private ControllerInputs inputs;
    public float Steering;
    public float Accel;
    public float Footbrake;
    public float Handbrake;

    public TMPro.TMP_Text InputText;
    public float InputTextRefreshRate = 10;
    private float inputTextRefreshTimeElapsed = 0f;
    private float? inputTextTargetRate;
    private float inputTextTargetTime = 0f;

    // Called when the script is first activated.
    private void Awake()
    {
        // Prepare input action scripts generated by inputactions.
        this.inputs = new ControllerInputs();
    }

    // Start is called before the first frame update
    void Start() { }

    // Update is called once per frame
    void Update()
    {
        // Read Inputs
        {
            var controller = this.inputs.Controller;
            Steering = controller.Steering.ReadValue<float>();
            Accel= controller.Accel.ReadValue<float>();
            Footbrake = controller.Footbrake.ReadValue<float>();
            Handbrake = controller.Handbrake.ReadValue<float>();
        }

        // Publish Inputs
        if (publisher != null)
        {
            publisher.Steering = Steering;
            publisher.Accel = Accel;
            publisher.Footbrake = Footbrake;
            publisher.Handbrake = Handbrake;
        }

        // Output Inputs
        if (InputText != null)
        {
            if (this.inputTextTargetRate != this.InputTextRefreshRate)
            {
                this.inputTextTargetRate = this.InputTextRefreshRate;
                this.inputTextTargetTime = 1f / this.inputTextTargetRate.Value;
            }

            this.inputTextRefreshTimeElapsed += Time.deltaTime;

            if (this.inputTextRefreshTimeElapsed >= this.inputTextTargetTime)
            {
                this.inputTextRefreshTimeElapsed -= this.inputTextTargetTime;

                string text = "";
                text += "Å° Controller Inputs";
                text += "\nSteering: " + this.Steering;
                text += "\nAccel: " + this.Accel;
                text += "\nFootbrake: " + this.Footbrake;
                text += "\nHandbrake: " + this.Handbrake;
                text += "\n";
                text += "Å° Key Binds";
                text += "\nSteering: A or D";
                text += "\nAccel: W";
                text += "\nFootbrake: Space";
                text += "\nHandbrake: Shift";
                InputText.text = text;
            }
        }
    }

    private void OnEnable()
    {
        // Input actions must be enabled.
        this.inputs.Enable();
    }
    private void OnDisable()
    {
        this.inputs.Disable();
    }
}
