/*
 * intdash API specification
 *
 * ## ベースURL  ベースURLは以下のとおりです。APIエンドポイントはこのベースURLから始まります。  ``` https://<host>/api ``` エンドポイント例: ``` https://example.intdash.jp/api/v1/measurements https://example.intdash.jp/api/media/videos ```  ## レスポンスのステータスコード  サーバーからクライアントに返却されるHTTPレスポンスのステータスコードは以下のとおりです。   | コード                    | 説明                                                                  | |:- -- -- -- -- -- -- -- -- -- -- -- -- -|:- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -| | 101 Switching Protocols   | サーバーはプロトコルを切り替えます。                                  | | 200 OK                    | リクエストは成功しました。                                            | | 201 Created               | 新しいリソースが作成されました。                                      | | 204 No Content            | リクエストは成功しました。返却するコンテンツはありません。            | | 400 Bad Request           | 構文が正しくないなどの理由により、リクエストは処理できませんでした。  | | 401 Unauthorized          | リクエストには認証が必要です。                                        | | 403 Forbidden             | アクセス権がないなどの理由により、リクエストは拒否されました。        | | 404 Not Found             | APIまたはリソースが見つかりません。                                   | | 405 Method Not Allowed    | 指定されたメソッドは許可されていません。                              | | 409 Conflict              | 既存のリソースとのコンフリクトのため、リクエストは失敗しました。      | | 500 Internal Server Error | サーバーで予期しないエラーが発生したため、リクエストは失敗しました。  |   ## 注意 リクエストボディのJSONでは、キーの大文字と小文字は区別されません。 従って、以下の2つのリクエストは同じものと見なされます。  ```  {   \"username\" : \"username\",   \"password\" : \"password\" }  ```   ```  {   \"Username\" : \"username\",   \"Password\" : \"password\" }  ```
 *
 * The version of the OpenAPI document: v2.4.0-next-4a4316946
 * Contact: VM2M-support@aptpod.co.jp
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = intdash.Client.FileParameter;
using OpenAPIDateConverter = intdash.Client.OpenAPIDateConverter;

namespace intdash.Model
{
    /// <summary>
    /// EdgeConnectionUpstream
    /// </summary>
    [DataContract(Name = "EdgeConnectionUpstream")]
    public partial class EdgeConnectionUpstream : IEquatable<EdgeConnectionUpstream>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EdgeConnectionUpstream" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EdgeConnectionUpstream() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EdgeConnectionUpstream" /> class.
        /// </summary>
        /// <param name="streamId">アップストリームのストリームID (required).</param>
        /// <param name="measurementUuid">アップストリームの計測UUID (required).</param>
        /// <param name="srcEdgeUuid">アップストリームの送信元エッジUUID (required).</param>
        /// <param name="resend">* &#x60;true&#x60; : このアップストリームは再送です。 * &#x60;false&#x60; : このアップストリームは再送ではありません。 (required).</param>
        /// <param name="store">* &#x60;true&#x60; : このアップストリームで送信されたデータポイントはサーバーに保存されます。 * &#x60;false&#x60; : このアップストリームで送信されたデータポイントはサーバーに保存されません。 (required).</param>
        /// <param name="lastReceivedAt">アップストリームで最後にデータポイントが送信された日時。 実際の最後のデータポイント送信よりも最大で10秒後の値となる場合があります。 (required).</param>
        /// <param name="receivedCloseRequest">* &#x60;true&#x60; : このアップストリームについてのclose requestを受信済みです。 * &#x60;false&#x60; : このアップストリームについてのclose requestは受信していません。 (required).</param>
        /// <param name="createdAt">アップストリームが作成された日時 (required).</param>
        /// <param name="updatedAt">アップストリームの最終更新日時 (required).</param>
        public EdgeConnectionUpstream(int streamId = default(int), string measurementUuid = default(string), string srcEdgeUuid = default(string), bool resend = default(bool), bool store = default(bool), string lastReceivedAt = default(string), bool receivedCloseRequest = default(bool), string createdAt = default(string), string updatedAt = default(string))
        {
            this.StreamId = streamId;
            // to ensure "measurementUuid" is required (not null)
            if (measurementUuid == null)
            {
                throw new ArgumentNullException("measurementUuid is a required property for EdgeConnectionUpstream and cannot be null");
            }
            this.MeasurementUuid = measurementUuid;
            // to ensure "srcEdgeUuid" is required (not null)
            if (srcEdgeUuid == null)
            {
                throw new ArgumentNullException("srcEdgeUuid is a required property for EdgeConnectionUpstream and cannot be null");
            }
            this.SrcEdgeUuid = srcEdgeUuid;
            this.Resend = resend;
            this.Store = store;
            // to ensure "lastReceivedAt" is required (not null)
            if (lastReceivedAt == null)
            {
                throw new ArgumentNullException("lastReceivedAt is a required property for EdgeConnectionUpstream and cannot be null");
            }
            this.LastReceivedAt = lastReceivedAt;
            this.ReceivedCloseRequest = receivedCloseRequest;
            // to ensure "createdAt" is required (not null)
            if (createdAt == null)
            {
                throw new ArgumentNullException("createdAt is a required property for EdgeConnectionUpstream and cannot be null");
            }
            this.CreatedAt = createdAt;
            // to ensure "updatedAt" is required (not null)
            if (updatedAt == null)
            {
                throw new ArgumentNullException("updatedAt is a required property for EdgeConnectionUpstream and cannot be null");
            }
            this.UpdatedAt = updatedAt;
        }

        /// <summary>
        /// アップストリームのストリームID
        /// </summary>
        /// <value>アップストリームのストリームID</value>
        [DataMember(Name = "stream_id", IsRequired = true, EmitDefaultValue = true)]
        public int StreamId { get; set; }

        /// <summary>
        /// アップストリームの計測UUID
        /// </summary>
        /// <value>アップストリームの計測UUID</value>
        [DataMember(Name = "measurement_uuid", IsRequired = true, EmitDefaultValue = true)]
        public string MeasurementUuid { get; set; }

        /// <summary>
        /// アップストリームの送信元エッジUUID
        /// </summary>
        /// <value>アップストリームの送信元エッジUUID</value>
        [DataMember(Name = "src_edge_uuid", IsRequired = true, EmitDefaultValue = true)]
        public string SrcEdgeUuid { get; set; }

        /// <summary>
        /// * &#x60;true&#x60; : このアップストリームは再送です。 * &#x60;false&#x60; : このアップストリームは再送ではありません。
        /// </summary>
        /// <value>* &#x60;true&#x60; : このアップストリームは再送です。 * &#x60;false&#x60; : このアップストリームは再送ではありません。</value>
        [DataMember(Name = "resend", IsRequired = true, EmitDefaultValue = true)]
        public bool Resend { get; set; }

        /// <summary>
        /// * &#x60;true&#x60; : このアップストリームで送信されたデータポイントはサーバーに保存されます。 * &#x60;false&#x60; : このアップストリームで送信されたデータポイントはサーバーに保存されません。
        /// </summary>
        /// <value>* &#x60;true&#x60; : このアップストリームで送信されたデータポイントはサーバーに保存されます。 * &#x60;false&#x60; : このアップストリームで送信されたデータポイントはサーバーに保存されません。</value>
        [DataMember(Name = "store", IsRequired = true, EmitDefaultValue = true)]
        public bool Store { get; set; }

        /// <summary>
        /// アップストリームで最後にデータポイントが送信された日時。 実際の最後のデータポイント送信よりも最大で10秒後の値となる場合があります。
        /// </summary>
        /// <value>アップストリームで最後にデータポイントが送信された日時。 実際の最後のデータポイント送信よりも最大で10秒後の値となる場合があります。</value>
        [DataMember(Name = "last_received_at", IsRequired = true, EmitDefaultValue = true)]
        public string LastReceivedAt { get; set; }

        /// <summary>
        /// * &#x60;true&#x60; : このアップストリームについてのclose requestを受信済みです。 * &#x60;false&#x60; : このアップストリームについてのclose requestは受信していません。
        /// </summary>
        /// <value>* &#x60;true&#x60; : このアップストリームについてのclose requestを受信済みです。 * &#x60;false&#x60; : このアップストリームについてのclose requestは受信していません。</value>
        [DataMember(Name = "received_close_request", IsRequired = true, EmitDefaultValue = true)]
        public bool ReceivedCloseRequest { get; set; }

        /// <summary>
        /// アップストリームが作成された日時
        /// </summary>
        /// <value>アップストリームが作成された日時</value>
        [DataMember(Name = "created_at", IsRequired = true, EmitDefaultValue = true)]
        public string CreatedAt { get; set; }

        /// <summary>
        /// アップストリームの最終更新日時
        /// </summary>
        /// <value>アップストリームの最終更新日時</value>
        [DataMember(Name = "updated_at", IsRequired = true, EmitDefaultValue = true)]
        public string UpdatedAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EdgeConnectionUpstream {\n");
            sb.Append("  StreamId: ").Append(StreamId).Append("\n");
            sb.Append("  MeasurementUuid: ").Append(MeasurementUuid).Append("\n");
            sb.Append("  SrcEdgeUuid: ").Append(SrcEdgeUuid).Append("\n");
            sb.Append("  Resend: ").Append(Resend).Append("\n");
            sb.Append("  Store: ").Append(Store).Append("\n");
            sb.Append("  LastReceivedAt: ").Append(LastReceivedAt).Append("\n");
            sb.Append("  ReceivedCloseRequest: ").Append(ReceivedCloseRequest).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EdgeConnectionUpstream);
        }

        /// <summary>
        /// Returns true if EdgeConnectionUpstream instances are equal
        /// </summary>
        /// <param name="input">Instance of EdgeConnectionUpstream to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EdgeConnectionUpstream input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.StreamId == input.StreamId ||
                    this.StreamId.Equals(input.StreamId)
                ) && 
                (
                    this.MeasurementUuid == input.MeasurementUuid ||
                    (this.MeasurementUuid != null &&
                    this.MeasurementUuid.Equals(input.MeasurementUuid))
                ) && 
                (
                    this.SrcEdgeUuid == input.SrcEdgeUuid ||
                    (this.SrcEdgeUuid != null &&
                    this.SrcEdgeUuid.Equals(input.SrcEdgeUuid))
                ) && 
                (
                    this.Resend == input.Resend ||
                    this.Resend.Equals(input.Resend)
                ) && 
                (
                    this.Store == input.Store ||
                    this.Store.Equals(input.Store)
                ) && 
                (
                    this.LastReceivedAt == input.LastReceivedAt ||
                    (this.LastReceivedAt != null &&
                    this.LastReceivedAt.Equals(input.LastReceivedAt))
                ) && 
                (
                    this.ReceivedCloseRequest == input.ReceivedCloseRequest ||
                    this.ReceivedCloseRequest.Equals(input.ReceivedCloseRequest)
                ) && 
                (
                    this.CreatedAt == input.CreatedAt ||
                    (this.CreatedAt != null &&
                    this.CreatedAt.Equals(input.CreatedAt))
                ) && 
                (
                    this.UpdatedAt == input.UpdatedAt ||
                    (this.UpdatedAt != null &&
                    this.UpdatedAt.Equals(input.UpdatedAt))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.StreamId.GetHashCode();
                if (this.MeasurementUuid != null)
                {
                    hashCode = (hashCode * 59) + this.MeasurementUuid.GetHashCode();
                }
                if (this.SrcEdgeUuid != null)
                {
                    hashCode = (hashCode * 59) + this.SrcEdgeUuid.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Resend.GetHashCode();
                hashCode = (hashCode * 59) + this.Store.GetHashCode();
                if (this.LastReceivedAt != null)
                {
                    hashCode = (hashCode * 59) + this.LastReceivedAt.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.ReceivedCloseRequest.GetHashCode();
                if (this.CreatedAt != null)
                {
                    hashCode = (hashCode * 59) + this.CreatedAt.GetHashCode();
                }
                if (this.UpdatedAt != null)
                {
                    hashCode = (hashCode * 59) + this.UpdatedAt.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
