/*
 * intdash API specification
 *
 * ## ベースURL  ベースURLは以下のとおりです。APIエンドポイントはこのベースURLから始まります。  ``` https://<host>/api ``` エンドポイント例: ``` https://example.intdash.jp/api/v1/measurements https://example.intdash.jp/api/media/videos ```  ## レスポンスのステータスコード  サーバーからクライアントに返却されるHTTPレスポンスのステータスコードは以下のとおりです。   | コード                    | 説明                                                                  | |:- -- -- -- -- -- -- -- -- -- -- -- -- -|:- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -| | 101 Switching Protocols   | サーバーはプロトコルを切り替えます。                                  | | 200 OK                    | リクエストは成功しました。                                            | | 201 Created               | 新しいリソースが作成されました。                                      | | 204 No Content            | リクエストは成功しました。返却するコンテンツはありません。            | | 400 Bad Request           | 構文が正しくないなどの理由により、リクエストは処理できませんでした。  | | 401 Unauthorized          | リクエストには認証が必要です。                                        | | 403 Forbidden             | アクセス権がないなどの理由により、リクエストは拒否されました。        | | 404 Not Found             | APIまたはリソースが見つかりません。                                   | | 405 Method Not Allowed    | 指定されたメソッドは許可されていません。                              | | 409 Conflict              | 既存のリソースとのコンフリクトのため、リクエストは失敗しました。      | | 500 Internal Server Error | サーバーで予期しないエラーが発生したため、リクエストは失敗しました。  |   ## 注意 リクエストボディのJSONでは、キーの大文字と小文字は区別されません。 従って、以下の2つのリクエストは同じものと見なされます。  ```  {   \"username\" : \"username\",   \"password\" : \"password\" }  ```   ```  {   \"Username\" : \"username\",   \"Password\" : \"password\" }  ```
 *
 * The version of the OpenAPI document: v2.4.0-next-4a4316946
 * Contact: VM2M-support@aptpod.co.jp
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = intdash.Client.FileParameter;
using OpenAPIDateConverter = intdash.Client.OpenAPIDateConverter;

namespace intdash.Model
{
    /// <summary>
    /// MeasurementUploadPostResponse
    /// </summary>
    [DataContract(Name = "MeasurementUploadPostResponse")]
    public partial class MeasurementUploadPostResponse : IEquatable<MeasurementUploadPostResponse>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MeasurementUploadPostResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MeasurementUploadPostResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MeasurementUploadPostResponse" /> class.
        /// </summary>
        /// <param name="measUploadUuid">計測アップロードのUUID (required).</param>
        /// <param name="jobUuid">計測への変換ジョブのUUID.</param>
        /// <param name="fileName">アップロードされたファイルのファイル名 (required).</param>
        public MeasurementUploadPostResponse(string measUploadUuid = default(string), string jobUuid = default(string), string fileName = default(string))
        {
            // to ensure "measUploadUuid" is required (not null)
            if (measUploadUuid == null)
            {
                throw new ArgumentNullException("measUploadUuid is a required property for MeasurementUploadPostResponse and cannot be null");
            }
            this.MeasUploadUuid = measUploadUuid;
            // to ensure "fileName" is required (not null)
            if (fileName == null)
            {
                throw new ArgumentNullException("fileName is a required property for MeasurementUploadPostResponse and cannot be null");
            }
            this.FileName = fileName;
            this.JobUuid = jobUuid;
        }

        /// <summary>
        /// 計測アップロードのUUID
        /// </summary>
        /// <value>計測アップロードのUUID</value>
        [DataMember(Name = "meas_upload_uuid", IsRequired = true, EmitDefaultValue = true)]
        [Obsolete]
        public string MeasUploadUuid { get; set; }

        /// <summary>
        /// 計測への変換ジョブのUUID
        /// </summary>
        /// <value>計測への変換ジョブのUUID</value>
        [DataMember(Name = "job_uuid", EmitDefaultValue = false)]
        public string JobUuid { get; set; }

        /// <summary>
        /// アップロードされたファイルのファイル名
        /// </summary>
        /// <value>アップロードされたファイルのファイル名</value>
        [DataMember(Name = "file_name", IsRequired = true, EmitDefaultValue = true)]
        public string FileName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MeasurementUploadPostResponse {\n");
            sb.Append("  MeasUploadUuid: ").Append(MeasUploadUuid).Append("\n");
            sb.Append("  JobUuid: ").Append(JobUuid).Append("\n");
            sb.Append("  FileName: ").Append(FileName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MeasurementUploadPostResponse);
        }

        /// <summary>
        /// Returns true if MeasurementUploadPostResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of MeasurementUploadPostResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MeasurementUploadPostResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.MeasUploadUuid == input.MeasUploadUuid ||
                    (this.MeasUploadUuid != null &&
                    this.MeasUploadUuid.Equals(input.MeasUploadUuid))
                ) && 
                (
                    this.JobUuid == input.JobUuid ||
                    (this.JobUuid != null &&
                    this.JobUuid.Equals(input.JobUuid))
                ) && 
                (
                    this.FileName == input.FileName ||
                    (this.FileName != null &&
                    this.FileName.Equals(input.FileName))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.MeasUploadUuid != null)
                {
                    hashCode = (hashCode * 59) + this.MeasUploadUuid.GetHashCode();
                }
                if (this.JobUuid != null)
                {
                    hashCode = (hashCode * 59) + this.JobUuid.GetHashCode();
                }
                if (this.FileName != null)
                {
                    hashCode = (hashCode * 59) + this.FileName.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
