/*
 * intdash API specification
 *
 * ## ベースURL  ベースURLは以下のとおりです。APIエンドポイントはこのベースURLから始まります。  ``` https://<host>/api ``` エンドポイント例: ``` https://example.intdash.jp/api/v1/measurements https://example.intdash.jp/api/media/videos ```  ## レスポンスのステータスコード  サーバーからクライアントに返却されるHTTPレスポンスのステータスコードは以下のとおりです。   | コード                    | 説明                                                                  | |:- -- -- -- -- -- -- -- -- -- -- -- -- -|:- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -| | 101 Switching Protocols   | サーバーはプロトコルを切り替えます。                                  | | 200 OK                    | リクエストは成功しました。                                            | | 201 Created               | 新しいリソースが作成されました。                                      | | 204 No Content            | リクエストは成功しました。返却するコンテンツはありません。            | | 400 Bad Request           | 構文が正しくないなどの理由により、リクエストは処理できませんでした。  | | 401 Unauthorized          | リクエストには認証が必要です。                                        | | 403 Forbidden             | アクセス権がないなどの理由により、リクエストは拒否されました。        | | 404 Not Found             | APIまたはリソースが見つかりません。                                   | | 405 Method Not Allowed    | 指定されたメソッドは許可されていません。                              | | 409 Conflict              | 既存のリソースとのコンフリクトのため、リクエストは失敗しました。      | | 500 Internal Server Error | サーバーで予期しないエラーが発生したため、リクエストは失敗しました。  |   ## 注意 リクエストボディのJSONでは、キーの大文字と小文字は区別されません。 従って、以下の2つのリクエストは同じものと見なされます。  ```  {   \"username\" : \"username\",   \"password\" : \"password\" }  ```   ```  {   \"Username\" : \"username\",   \"Password\" : \"password\" }  ```
 *
 * The version of the OpenAPI document: v2.4.0-next-4a4316946
 * Contact: VM2M-support@aptpod.co.jp
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = intdash.Client.FileParameter;
using OpenAPIDateConverter = intdash.Client.OpenAPIDateConverter;

namespace intdash.Model
{
    /// <summary>
    /// CreateOAuth2ClientClientCredentialsRequest
    /// </summary>
    [DataContract(Name = "CreateOAuth2ClientClientCredentialsRequest")]
    public partial class CreateOAuth2ClientClientCredentialsRequest : IEquatable<CreateOAuth2ClientClientCredentialsRequest>
    {
        /// <summary>
        /// グラントタイプ
        /// </summary>
        /// <value>グラントタイプ</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum GrantTypeEnum
        {
            /// <summary>
            /// Enum AuthorizationCode for value: authorization_code
            /// </summary>
            [EnumMember(Value = "authorization_code")]
            AuthorizationCode = 1,

            /// <summary>
            /// Enum ClientCredentials for value: client_credentials
            /// </summary>
            [EnumMember(Value = "client_credentials")]
            ClientCredentials = 2

        }


        /// <summary>
        /// グラントタイプ
        /// </summary>
        /// <value>グラントタイプ</value>
        [DataMember(Name = "grant_type", IsRequired = true, EmitDefaultValue = true)]
        public GrantTypeEnum GrantType { get; set; }
        /// <summary>
        /// トークンエンドポイントの認証方式
        /// </summary>
        /// <value>トークンエンドポイントの認証方式</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TokenEndpointAuthMethodEnum
        {
            /// <summary>
            /// Enum ClientSecretPost for value: client_secret_post
            /// </summary>
            [EnumMember(Value = "client_secret_post")]
            ClientSecretPost = 1,

            /// <summary>
            /// Enum TlsClientAuth for value: tls_client_auth
            /// </summary>
            [EnumMember(Value = "tls_client_auth")]
            TlsClientAuth = 2

        }


        /// <summary>
        /// トークンエンドポイントの認証方式
        /// </summary>
        /// <value>トークンエンドポイントの認証方式</value>
        [DataMember(Name = "token_endpoint_auth_method", IsRequired = true, EmitDefaultValue = true)]
        public TokenEndpointAuthMethodEnum TokenEndpointAuthMethod { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateOAuth2ClientClientCredentialsRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateOAuth2ClientClientCredentialsRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateOAuth2ClientClientCredentialsRequest" /> class.
        /// </summary>
        /// <param name="name">名前 (required).</param>
        /// <param name="grantType">グラントタイプ (required).</param>
        /// <param name="tokenEndpointAuthMethod">トークンエンドポイントの認証方式 (required) (default to TokenEndpointAuthMethodEnum.ClientSecretPost).</param>
        /// <param name="tlsClientAuthSubjectDn">TLSクライアント認証のサブジェクトDN.</param>
        public CreateOAuth2ClientClientCredentialsRequest(string name = default(string), GrantTypeEnum grantType = default(GrantTypeEnum), TokenEndpointAuthMethodEnum tokenEndpointAuthMethod = TokenEndpointAuthMethodEnum.ClientSecretPost, string tlsClientAuthSubjectDn = default(string))
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for CreateOAuth2ClientClientCredentialsRequest and cannot be null");
            }
            this.Name = name;
            this.GrantType = grantType;
            this.TokenEndpointAuthMethod = tokenEndpointAuthMethod;
            this.TlsClientAuthSubjectDn = tlsClientAuthSubjectDn;
        }

        /// <summary>
        /// 名前
        /// </summary>
        /// <value>名前</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// TLSクライアント認証のサブジェクトDN
        /// </summary>
        /// <value>TLSクライアント認証のサブジェクトDN</value>
        [DataMember(Name = "tls_client_auth_subject_dn", EmitDefaultValue = false)]
        public string TlsClientAuthSubjectDn { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateOAuth2ClientClientCredentialsRequest {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  GrantType: ").Append(GrantType).Append("\n");
            sb.Append("  TokenEndpointAuthMethod: ").Append(TokenEndpointAuthMethod).Append("\n");
            sb.Append("  TlsClientAuthSubjectDn: ").Append(TlsClientAuthSubjectDn).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CreateOAuth2ClientClientCredentialsRequest);
        }

        /// <summary>
        /// Returns true if CreateOAuth2ClientClientCredentialsRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of CreateOAuth2ClientClientCredentialsRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateOAuth2ClientClientCredentialsRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.GrantType == input.GrantType ||
                    this.GrantType.Equals(input.GrantType)
                ) && 
                (
                    this.TokenEndpointAuthMethod == input.TokenEndpointAuthMethod ||
                    this.TokenEndpointAuthMethod.Equals(input.TokenEndpointAuthMethod)
                ) && 
                (
                    this.TlsClientAuthSubjectDn == input.TlsClientAuthSubjectDn ||
                    (this.TlsClientAuthSubjectDn != null &&
                    this.TlsClientAuthSubjectDn.Equals(input.TlsClientAuthSubjectDn))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Name != null)
                {
                    hashCode = (hashCode * 59) + this.Name.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.GrantType.GetHashCode();
                hashCode = (hashCode * 59) + this.TokenEndpointAuthMethod.GetHashCode();
                if (this.TlsClientAuthSubjectDn != null)
                {
                    hashCode = (hashCode * 59) + this.TlsClientAuthSubjectDn.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
