/*
 * intdash API specification
 *
 * ## ベースURL  ベースURLは以下のとおりです。APIエンドポイントはこのベースURLから始まります。  ``` https://<host>/api ``` エンドポイント例: ``` https://example.intdash.jp/api/v1/measurements https://example.intdash.jp/api/media/videos ```  ## レスポンスのステータスコード  サーバーからクライアントに返却されるHTTPレスポンスのステータスコードは以下のとおりです。   | コード                    | 説明                                                                  | |:- -- -- -- -- -- -- -- -- -- -- -- -- -|:- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -| | 101 Switching Protocols   | サーバーはプロトコルを切り替えます。                                  | | 200 OK                    | リクエストは成功しました。                                            | | 201 Created               | 新しいリソースが作成されました。                                      | | 204 No Content            | リクエストは成功しました。返却するコンテンツはありません。            | | 400 Bad Request           | 構文が正しくないなどの理由により、リクエストは処理できませんでした。  | | 401 Unauthorized          | リクエストには認証が必要です。                                        | | 403 Forbidden             | アクセス権がないなどの理由により、リクエストは拒否されました。        | | 404 Not Found             | APIまたはリソースが見つかりません。                                   | | 405 Method Not Allowed    | 指定されたメソッドは許可されていません。                              | | 409 Conflict              | 既存のリソースとのコンフリクトのため、リクエストは失敗しました。      | | 500 Internal Server Error | サーバーで予期しないエラーが発生したため、リクエストは失敗しました。  |   ## 注意 リクエストボディのJSONでは、キーの大文字と小文字は区別されません。 従って、以下の2つのリクエストは同じものと見なされます。  ```  {   \"username\" : \"username\",   \"password\" : \"password\" }  ```   ```  {   \"Username\" : \"username\",   \"Password\" : \"password\" }  ```
 *
 * The version of the OpenAPI document: v2.4.0-next-4a4316946
 * Contact: VM2M-support@aptpod.co.jp
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = intdash.Client.FileParameter;
using OpenAPIDateConverter = intdash.Client.OpenAPIDateConverter;

namespace intdash.Model
{
    /// <summary>
    /// EdgeConnectionEdge
    /// </summary>
    [DataContract(Name = "EdgeConnectionEdge")]
    public partial class EdgeConnectionEdge : IEquatable<EdgeConnectionEdge>
    {
        /// <summary>
        /// エッジのタイプ
        /// </summary>
        /// <value>エッジのタイプ</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TypeEnum
        {
            /// <summary>
            /// Enum User for value: user
            /// </summary>
            [EnumMember(Value = "user")]
            User = 1,

            /// <summary>
            /// Enum Device for value: device
            /// </summary>
            [EnumMember(Value = "device")]
            Device = 2

        }


        /// <summary>
        /// エッジのタイプ
        /// </summary>
        /// <value>エッジのタイプ</value>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public TypeEnum Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="EdgeConnectionEdge" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EdgeConnectionEdge() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EdgeConnectionEdge" /> class.
        /// </summary>
        /// <param name="uuid">エッジのUUID (required).</param>
        /// <param name="name">エッジの名前 (required).</param>
        /// <param name="nickname">エッジの表示名 (required).</param>
        /// <param name="description">エッジの説明 (required).</param>
        /// <param name="disabled">* &#x60;true&#x60; : このエッジは無効化されています。 * &#x60;false&#x60; : このエッジは有効です。 (required).</param>
        /// <param name="_internal">* &#x60;true&#x60; : このエッジは内部エッジ（システム内部で使用される特別なエッジ）です。   このエッジの変更や削除はできません。 * &#x60;false&#x60; : このエッジは内部エッジではありません。 (required).</param>
        /// <param name="_protected">* &#x60;true&#x60; : このエッジは保護されています。このエッジの変更や削除はできません。 * &#x60;false&#x60; : このエッジは保護されていません。 (required).</param>
        /// <param name="type">エッジのタイプ (required).</param>
        /// <param name="lastLoginAt">エッジが最後にログインした日時 (required).</param>
        /// <param name="lastLivedAt">サーバーがこのエッジ接続を確認できた最後の日時。 エッジとサーバーがWebSocketで接続されている間、この値は数秒おきに最新の日時に更新されます。 WebSocketが切断されると、それ以上更新されなくなります。 更新は数秒おきであるため、WebSocketが切断された場合に その切断の時刻が正確に記録されるわけではありません。 (required).</param>
        /// <param name="createdAt">エッジが作成された日時 (required).</param>
        /// <param name="updatedAt">エッジの最終更新日時 (required).</param>
        public EdgeConnectionEdge(string uuid = default(string), string name = default(string), string nickname = default(string), string description = default(string), bool disabled = default(bool), bool _internal = default(bool), bool _protected = default(bool), TypeEnum type = default(TypeEnum), string lastLoginAt = default(string), string lastLivedAt = default(string), string createdAt = default(string), string updatedAt = default(string))
        {
            // to ensure "uuid" is required (not null)
            if (uuid == null)
            {
                throw new ArgumentNullException("uuid is a required property for EdgeConnectionEdge and cannot be null");
            }
            this.Uuid = uuid;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for EdgeConnectionEdge and cannot be null");
            }
            this.Name = name;
            // to ensure "nickname" is required (not null)
            if (nickname == null)
            {
                throw new ArgumentNullException("nickname is a required property for EdgeConnectionEdge and cannot be null");
            }
            this.Nickname = nickname;
            // to ensure "description" is required (not null)
            if (description == null)
            {
                throw new ArgumentNullException("description is a required property for EdgeConnectionEdge and cannot be null");
            }
            this.Description = description;
            this.Disabled = disabled;
            this.Internal = _internal;
            this.Protected = _protected;
            this.Type = type;
            // to ensure "lastLoginAt" is required (not null)
            if (lastLoginAt == null)
            {
                throw new ArgumentNullException("lastLoginAt is a required property for EdgeConnectionEdge and cannot be null");
            }
            this.LastLoginAt = lastLoginAt;
            // to ensure "lastLivedAt" is required (not null)
            if (lastLivedAt == null)
            {
                throw new ArgumentNullException("lastLivedAt is a required property for EdgeConnectionEdge and cannot be null");
            }
            this.LastLivedAt = lastLivedAt;
            // to ensure "createdAt" is required (not null)
            if (createdAt == null)
            {
                throw new ArgumentNullException("createdAt is a required property for EdgeConnectionEdge and cannot be null");
            }
            this.CreatedAt = createdAt;
            // to ensure "updatedAt" is required (not null)
            if (updatedAt == null)
            {
                throw new ArgumentNullException("updatedAt is a required property for EdgeConnectionEdge and cannot be null");
            }
            this.UpdatedAt = updatedAt;
        }

        /// <summary>
        /// エッジのUUID
        /// </summary>
        /// <value>エッジのUUID</value>
        [DataMember(Name = "uuid", IsRequired = true, EmitDefaultValue = true)]
        public string Uuid { get; set; }

        /// <summary>
        /// エッジの名前
        /// </summary>
        /// <value>エッジの名前</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// エッジの表示名
        /// </summary>
        /// <value>エッジの表示名</value>
        [DataMember(Name = "nickname", IsRequired = true, EmitDefaultValue = true)]
        public string Nickname { get; set; }

        /// <summary>
        /// エッジの説明
        /// </summary>
        /// <value>エッジの説明</value>
        [DataMember(Name = "description", IsRequired = true, EmitDefaultValue = true)]
        public string Description { get; set; }

        /// <summary>
        /// * &#x60;true&#x60; : このエッジは無効化されています。 * &#x60;false&#x60; : このエッジは有効です。
        /// </summary>
        /// <value>* &#x60;true&#x60; : このエッジは無効化されています。 * &#x60;false&#x60; : このエッジは有効です。</value>
        [DataMember(Name = "disabled", IsRequired = true, EmitDefaultValue = true)]
        public bool Disabled { get; set; }

        /// <summary>
        /// * &#x60;true&#x60; : このエッジは内部エッジ（システム内部で使用される特別なエッジ）です。   このエッジの変更や削除はできません。 * &#x60;false&#x60; : このエッジは内部エッジではありません。
        /// </summary>
        /// <value>* &#x60;true&#x60; : このエッジは内部エッジ（システム内部で使用される特別なエッジ）です。   このエッジの変更や削除はできません。 * &#x60;false&#x60; : このエッジは内部エッジではありません。</value>
        [DataMember(Name = "internal", IsRequired = true, EmitDefaultValue = true)]
        public bool Internal { get; set; }

        /// <summary>
        /// * &#x60;true&#x60; : このエッジは保護されています。このエッジの変更や削除はできません。 * &#x60;false&#x60; : このエッジは保護されていません。
        /// </summary>
        /// <value>* &#x60;true&#x60; : このエッジは保護されています。このエッジの変更や削除はできません。 * &#x60;false&#x60; : このエッジは保護されていません。</value>
        [DataMember(Name = "protected", IsRequired = true, EmitDefaultValue = true)]
        public bool Protected { get; set; }

        /// <summary>
        /// エッジが最後にログインした日時
        /// </summary>
        /// <value>エッジが最後にログインした日時</value>
        [DataMember(Name = "last_login_at", IsRequired = true, EmitDefaultValue = true)]
        public string LastLoginAt { get; set; }

        /// <summary>
        /// サーバーがこのエッジ接続を確認できた最後の日時。 エッジとサーバーがWebSocketで接続されている間、この値は数秒おきに最新の日時に更新されます。 WebSocketが切断されると、それ以上更新されなくなります。 更新は数秒おきであるため、WebSocketが切断された場合に その切断の時刻が正確に記録されるわけではありません。
        /// </summary>
        /// <value>サーバーがこのエッジ接続を確認できた最後の日時。 エッジとサーバーがWebSocketで接続されている間、この値は数秒おきに最新の日時に更新されます。 WebSocketが切断されると、それ以上更新されなくなります。 更新は数秒おきであるため、WebSocketが切断された場合に その切断の時刻が正確に記録されるわけではありません。</value>
        [DataMember(Name = "last_lived_at", IsRequired = true, EmitDefaultValue = true)]
        public string LastLivedAt { get; set; }

        /// <summary>
        /// エッジが作成された日時
        /// </summary>
        /// <value>エッジが作成された日時</value>
        [DataMember(Name = "created_at", IsRequired = true, EmitDefaultValue = true)]
        public string CreatedAt { get; set; }

        /// <summary>
        /// エッジの最終更新日時
        /// </summary>
        /// <value>エッジの最終更新日時</value>
        [DataMember(Name = "updated_at", IsRequired = true, EmitDefaultValue = true)]
        public string UpdatedAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EdgeConnectionEdge {\n");
            sb.Append("  Uuid: ").Append(Uuid).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Nickname: ").Append(Nickname).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Disabled: ").Append(Disabled).Append("\n");
            sb.Append("  Internal: ").Append(Internal).Append("\n");
            sb.Append("  Protected: ").Append(Protected).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  LastLoginAt: ").Append(LastLoginAt).Append("\n");
            sb.Append("  LastLivedAt: ").Append(LastLivedAt).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EdgeConnectionEdge);
        }

        /// <summary>
        /// Returns true if EdgeConnectionEdge instances are equal
        /// </summary>
        /// <param name="input">Instance of EdgeConnectionEdge to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EdgeConnectionEdge input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Uuid == input.Uuid ||
                    (this.Uuid != null &&
                    this.Uuid.Equals(input.Uuid))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Nickname == input.Nickname ||
                    (this.Nickname != null &&
                    this.Nickname.Equals(input.Nickname))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.Disabled == input.Disabled ||
                    this.Disabled.Equals(input.Disabled)
                ) && 
                (
                    this.Internal == input.Internal ||
                    this.Internal.Equals(input.Internal)
                ) && 
                (
                    this.Protected == input.Protected ||
                    this.Protected.Equals(input.Protected)
                ) && 
                (
                    this.Type == input.Type ||
                    this.Type.Equals(input.Type)
                ) && 
                (
                    this.LastLoginAt == input.LastLoginAt ||
                    (this.LastLoginAt != null &&
                    this.LastLoginAt.Equals(input.LastLoginAt))
                ) && 
                (
                    this.LastLivedAt == input.LastLivedAt ||
                    (this.LastLivedAt != null &&
                    this.LastLivedAt.Equals(input.LastLivedAt))
                ) && 
                (
                    this.CreatedAt == input.CreatedAt ||
                    (this.CreatedAt != null &&
                    this.CreatedAt.Equals(input.CreatedAt))
                ) && 
                (
                    this.UpdatedAt == input.UpdatedAt ||
                    (this.UpdatedAt != null &&
                    this.UpdatedAt.Equals(input.UpdatedAt))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Uuid != null)
                {
                    hashCode = (hashCode * 59) + this.Uuid.GetHashCode();
                }
                if (this.Name != null)
                {
                    hashCode = (hashCode * 59) + this.Name.GetHashCode();
                }
                if (this.Nickname != null)
                {
                    hashCode = (hashCode * 59) + this.Nickname.GetHashCode();
                }
                if (this.Description != null)
                {
                    hashCode = (hashCode * 59) + this.Description.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Disabled.GetHashCode();
                hashCode = (hashCode * 59) + this.Internal.GetHashCode();
                hashCode = (hashCode * 59) + this.Protected.GetHashCode();
                hashCode = (hashCode * 59) + this.Type.GetHashCode();
                if (this.LastLoginAt != null)
                {
                    hashCode = (hashCode * 59) + this.LastLoginAt.GetHashCode();
                }
                if (this.LastLivedAt != null)
                {
                    hashCode = (hashCode * 59) + this.LastLivedAt.GetHashCode();
                }
                if (this.CreatedAt != null)
                {
                    hashCode = (hashCode * 59) + this.CreatedAt.GetHashCode();
                }
                if (this.UpdatedAt != null)
                {
                    hashCode = (hashCode * 59) + this.UpdatedAt.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
