/*
 * intdash API specification
 *
 * ## ベースURL  ベースURLは以下のとおりです。APIエンドポイントはこのベースURLから始まります。  ``` https://<host>/api ``` エンドポイント例: ``` https://example.intdash.jp/api/v1/measurements https://example.intdash.jp/api/media/videos ```  ## レスポンスのステータスコード  サーバーからクライアントに返却されるHTTPレスポンスのステータスコードは以下のとおりです。   | コード                    | 説明                                                                  | |:- -- -- -- -- -- -- -- -- -- -- -- -- -|:- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -| | 101 Switching Protocols   | サーバーはプロトコルを切り替えます。                                  | | 200 OK                    | リクエストは成功しました。                                            | | 201 Created               | 新しいリソースが作成されました。                                      | | 204 No Content            | リクエストは成功しました。返却するコンテンツはありません。            | | 400 Bad Request           | 構文が正しくないなどの理由により、リクエストは処理できませんでした。  | | 401 Unauthorized          | リクエストには認証が必要です。                                        | | 403 Forbidden             | アクセス権がないなどの理由により、リクエストは拒否されました。        | | 404 Not Found             | APIまたはリソースが見つかりません。                                   | | 405 Method Not Allowed    | 指定されたメソッドは許可されていません。                              | | 409 Conflict              | 既存のリソースとのコンフリクトのため、リクエストは失敗しました。      | | 500 Internal Server Error | サーバーで予期しないエラーが発生したため、リクエストは失敗しました。  |   ## 注意 リクエストボディのJSONでは、キーの大文字と小文字は区別されません。 従って、以下の2つのリクエストは同じものと見なされます。  ```  {   \"username\" : \"username\",   \"password\" : \"password\" }  ```   ```  {   \"Username\" : \"username\",   \"Password\" : \"password\" }  ```
 *
 * The version of the OpenAPI document: v2.4.0-next-4a4316946
 * Contact: VM2M-support@aptpod.co.jp
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = intdash.Client.FileParameter;
using OpenAPIDateConverter = intdash.Client.OpenAPIDateConverter;

namespace intdash.Model
{
    /// <summary>
    /// EdgeConnectionAllOf
    /// </summary>
    [DataContract(Name = "EdgeConnection_allOf")]
    public partial class EdgeConnectionAllOf : IEquatable<EdgeConnectionAllOf>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EdgeConnectionAllOf" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EdgeConnectionAllOf() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EdgeConnectionAllOf" /> class.
        /// </summary>
        /// <param name="downstreams">ダウンストリームについての情報 (required).</param>
        /// <param name="upstreams">アップストリームについての情報 (required).</param>
        public EdgeConnectionAllOf(List<EdgeConnectionDownstream> downstreams = default(List<EdgeConnectionDownstream>), List<EdgeConnectionUpstream> upstreams = default(List<EdgeConnectionUpstream>))
        {
            // to ensure "downstreams" is required (not null)
            if (downstreams == null)
            {
                throw new ArgumentNullException("downstreams is a required property for EdgeConnectionAllOf and cannot be null");
            }
            this.Downstreams = downstreams;
            // to ensure "upstreams" is required (not null)
            if (upstreams == null)
            {
                throw new ArgumentNullException("upstreams is a required property for EdgeConnectionAllOf and cannot be null");
            }
            this.Upstreams = upstreams;
        }

        /// <summary>
        /// ダウンストリームについての情報
        /// </summary>
        /// <value>ダウンストリームについての情報</value>
        [DataMember(Name = "downstreams", IsRequired = true, EmitDefaultValue = true)]
        public List<EdgeConnectionDownstream> Downstreams { get; set; }

        /// <summary>
        /// アップストリームについての情報
        /// </summary>
        /// <value>アップストリームについての情報</value>
        [DataMember(Name = "upstreams", IsRequired = true, EmitDefaultValue = true)]
        public List<EdgeConnectionUpstream> Upstreams { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EdgeConnectionAllOf {\n");
            sb.Append("  Downstreams: ").Append(Downstreams).Append("\n");
            sb.Append("  Upstreams: ").Append(Upstreams).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EdgeConnectionAllOf);
        }

        /// <summary>
        /// Returns true if EdgeConnectionAllOf instances are equal
        /// </summary>
        /// <param name="input">Instance of EdgeConnectionAllOf to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EdgeConnectionAllOf input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Downstreams == input.Downstreams ||
                    this.Downstreams != null &&
                    input.Downstreams != null &&
                    this.Downstreams.SequenceEqual(input.Downstreams)
                ) && 
                (
                    this.Upstreams == input.Upstreams ||
                    this.Upstreams != null &&
                    input.Upstreams != null &&
                    this.Upstreams.SequenceEqual(input.Upstreams)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Downstreams != null)
                {
                    hashCode = (hashCode * 59) + this.Downstreams.GetHashCode();
                }
                if (this.Upstreams != null)
                {
                    hashCode = (hashCode * 59) + this.Upstreams.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
