/*
 * intdash API specification
 *
 * ## ベースURL  ベースURLは以下のとおりです。APIエンドポイントはこのベースURLから始まります。  ``` https://<host>/api ``` エンドポイント例: ``` https://example.intdash.jp/api/v1/measurements https://example.intdash.jp/api/media/videos ```  ## レスポンスのステータスコード  サーバーからクライアントに返却されるHTTPレスポンスのステータスコードは以下のとおりです。   | コード                    | 説明                                                                  | |:- -- -- -- -- -- -- -- -- -- -- -- -- -|:- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -| | 101 Switching Protocols   | サーバーはプロトコルを切り替えます。                                  | | 200 OK                    | リクエストは成功しました。                                            | | 201 Created               | 新しいリソースが作成されました。                                      | | 204 No Content            | リクエストは成功しました。返却するコンテンツはありません。            | | 400 Bad Request           | 構文が正しくないなどの理由により、リクエストは処理できませんでした。  | | 401 Unauthorized          | リクエストには認証が必要です。                                        | | 403 Forbidden             | アクセス権がないなどの理由により、リクエストは拒否されました。        | | 404 Not Found             | APIまたはリソースが見つかりません。                                   | | 405 Method Not Allowed    | 指定されたメソッドは許可されていません。                              | | 409 Conflict              | 既存のリソースとのコンフリクトのため、リクエストは失敗しました。      | | 500 Internal Server Error | サーバーで予期しないエラーが発生したため、リクエストは失敗しました。  |   ## 注意 リクエストボディのJSONでは、キーの大文字と小文字は区別されません。 従って、以下の2つのリクエストは同じものと見なされます。  ```  {   \"username\" : \"username\",   \"password\" : \"password\" }  ```   ```  {   \"Username\" : \"username\",   \"Password\" : \"password\" }  ```
 *
 * The version of the OpenAPI document: v2.4.0-next-4a4316946
 * Contact: VM2M-support@aptpod.co.jp
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = intdash.Client.FileParameter;
using OpenAPIDateConverter = intdash.Client.OpenAPIDateConverter;

namespace intdash.Model
{
    /// <summary>
    /// Playlist
    /// </summary>
    [DataContract(Name = "Playlist")]
    public partial class Playlist : IEquatable<Playlist>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Playlist" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Playlist() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Playlist" /> class.
        /// </summary>
        /// <param name="playlist">プレイリスト (required).</param>
        /// <param name="playlistWithEndlistTag">EXT-X-ENDLISTタグが付いたプレイリスト (required).</param>
        public Playlist(string playlist = default(string), string playlistWithEndlistTag = default(string))
        {
            // to ensure "playlist" is required (not null)
            if (playlist == null)
            {
                throw new ArgumentNullException("playlist is a required property for Playlist and cannot be null");
            }
            this._Playlist = playlist;
            // to ensure "playlistWithEndlistTag" is required (not null)
            if (playlistWithEndlistTag == null)
            {
                throw new ArgumentNullException("playlistWithEndlistTag is a required property for Playlist and cannot be null");
            }
            this.PlaylistWithEndlistTag = playlistWithEndlistTag;
        }

        /// <summary>
        /// プレイリスト
        /// </summary>
        /// <value>プレイリスト</value>
        [DataMember(Name = "playlist", IsRequired = true, EmitDefaultValue = true)]
        public string _Playlist { get; set; }

        /// <summary>
        /// EXT-X-ENDLISTタグが付いたプレイリスト
        /// </summary>
        /// <value>EXT-X-ENDLISTタグが付いたプレイリスト</value>
        [DataMember(Name = "playlist_with_endlist_tag", IsRequired = true, EmitDefaultValue = true)]
        public string PlaylistWithEndlistTag { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Playlist {\n");
            sb.Append("  _Playlist: ").Append(_Playlist).Append("\n");
            sb.Append("  PlaylistWithEndlistTag: ").Append(PlaylistWithEndlistTag).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Playlist);
        }

        /// <summary>
        /// Returns true if Playlist instances are equal
        /// </summary>
        /// <param name="input">Instance of Playlist to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Playlist input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this._Playlist == input._Playlist ||
                    (this._Playlist != null &&
                    this._Playlist.Equals(input._Playlist))
                ) && 
                (
                    this.PlaylistWithEndlistTag == input.PlaylistWithEndlistTag ||
                    (this.PlaylistWithEndlistTag != null &&
                    this.PlaylistWithEndlistTag.Equals(input.PlaylistWithEndlistTag))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this._Playlist != null)
                {
                    hashCode = (hashCode * 59) + this._Playlist.GetHashCode();
                }
                if (this.PlaylistWithEndlistTag != null)
                {
                    hashCode = (hashCode * 59) + this.PlaylistWithEndlistTag.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
